WIP
maplight/clc-ad-transparency pull request #30
Opened 2023-11-08 22:10 UTC by harlie

WIP, but I'm interested in feedback on this approach to inject instructions onto the list page vs patch package. This seems brittle (what if they change the selector) but isolates our code better vs patch package. 
<img width="971" alt="image" src="https://github.com/maplight/clc-ad-transparency/assets/1364700/4dd3712f-7470-4149-b4e8-e4910a07eb6e">

2023-11-09 18:01 UTC, jcoryalvernaz commented
@harlie Thanks for putting this together! I think this approach does what we need.

2023-11-15 18:51 UTC, harlie commented
@jcoryalvernaz - modified the approach to use [<Portal>](https://design-system-git-main-strapijs.vercel.app/?path=/docs/design-system-technical-components-portal--docs) instead. Added an instructions homepage and a settings page to allow for admin configuration. I think it's ready enough for a real review now

2023-11-27 19:30 UTC, jcoryalvernaz requested changes
Code LGTM. I have comments related to maintenance. Thanks!

2023-11-29 16:28 UTC, harlie commented on backend/src/plugins/instructions/admin/src/components/Injected/list-view-instructions.tsx
> +    const headerElement = document.querySelector('[data-strapi-header="true"]');
@jcoryalvernaz unfortunately there is no list view equivalent to useCMEditViewDataManager that I could find. Folks on the internet recommended diving into strapi's state to pull out data which I do in [this line here in a later commit](https://github.com/maplight/clc-ad-transparency/pull/30/commits/a473f8608f13104caeb0afec21e615c00ad64b16#diff-59963eb93ab42070147f2a6e378c78b34ba1c9345ef15709d7aa9c7126e0be6eL13:~:text=const%20apiID%20%3D%20useSelector((state%20%3A%20any)%20%3D%3E%20state%5B%22content%2Dmanager_listView%22%5D.contentType.apiID)%3B):

>  const apiID = useSelector((state : any) => state["content-manager_listView"].contentType.apiID);
I then use the apiID to fetch the appropriate content for that list page.

2023-11-29 16:30 UTC, harlie commented on backend/package.json
> +    "build:plugin": "cd ./src/plugins/ad-disclosure-report && yarn build && cd ../../../src/plugins/instructions && yarn build",
Probably not a bad idea. I can take a stab at it this week, mostly concerned about any migration needs.

2023-11-29 21:26 UTC, harlie commented
closing in favor of #44

2023-11-29 21:26 UTC, closed without merging